export default [
  "introduction_to_react_and_jsx",
  "state_and_event_handlers",
  "custom_hooks",
  "creating_reusable_components",
  "error_handling",
  "refs_and_the_dom",
  "effects_and_the_component_lifecycle",
  "managing_complex_state",
  "forms",
  "measuring_performance",
  "reducing_renders",
  "memoisation_within_components",
  "code_splitting_and_lazy_loading",
  "deferring_updates",
  "rendering_on_the_server",
]
