export default {
  introduction_to_react_and_jsx: "Introduction to React and JSX",
  state_and_event_handlers: "Making Components Interactive",
  custom_hooks: "Custom Hooks",
  creating_reusable_components: "Creating Reusable Components",
  error_handling: "Error Handling",
  refs_and_the_dom: "Refs, Portals, and the DOM",
  effects_and_the_component_lifecycle: "Effects and the Component Lifecycle",
  managing_complex_state: "Managing Complex State",
  forms: "Working with Forms",
  measuring_performance: "Measuring Performance",
  reducing_renders: "Reducing Renders",
  memoisation_within_components: "Memoisation within Components",
  code_splitting_and_lazy_loading: "Code Splitting and Lazy Loading",
  deferring_updates: "Deferring Updates",
  rendering_on_the_server: "Rendering on the Server",
}
